import 'package:decimal/decimal.dart';

import 'package:mine_storage/domain/entities/entities.dart';

Decimal dec(String value) => Decimal.parse(value);

TransactionLine ledgerLine({
  String id = 'line-1',
  String productId = 'product-1',
  String productName = 'Whole Milk 1L',
  String batchId = 'batch-1',
  String batchCode = 'L-2608-A',
  String quantityDelta = '-2.000',
  String? quantityBefore,
  String unitPrice = '1.80',
  String unitCostSnapshot = '1.10',
  String? batchUnitCost,
  String lineGross = '3.60',
  String lineCost = '2.20',
  DateTime? expiryDate,
  int sortOrder = 0,
}) => TransactionLine(
  id: id,
  transactionId: 'txn-1',
  productId: productId,
  batchId: batchId,
  batchCode: batchCode,
  productName: productName,
  unit: ProductUnit.piece,
  quantityDelta: dec(quantityDelta),
  quantityBefore: quantityBefore == null ? null : dec(quantityBefore),
  unitPrice: dec(unitPrice),
  unitCostSnapshot: dec(unitCostSnapshot),
  batchUnitCost: batchUnitCost == null ? null : dec(batchUnitCost),
  lineGross: dec(lineGross),
  lineCost: dec(lineCost),
  expiryDate: expiryDate,
  sortOrder: sortOrder,
);

TransactionFee ledgerFee({
  String id = 'fee-1',
  String name = 'Freight',
  FeeDirection direction = FeeDirection.sellerCost,
  FeeKind kind = FeeKind.fixed,
  String value = '6.00',
  String computedAmount = '6.00',
}) => TransactionFee(
  id: id,
  transactionId: 'txn-1',
  name: name,
  direction: direction,
  kind: kind,
  value: dec(value),
  computedAmount: dec(computedAmount),
);

TransactionMoney ledgerMoney({
  String itemsSubtotal = '35.80',
  String discountTotal = '0.00',
  String buyerChargeTotal = '0.00',
  String sellerCostTotal = '0.00',
  String passThroughTotal = '0.00',
  String buyerTotal = '35.80',
  String netRevenue = '35.80',
  String cogs = '25.00',
  String grossProfit = '10.80',
  String netProfit = '10.80',
  String netMargin = '0.296',
}) => TransactionMoney(
  itemsSubtotal: dec(itemsSubtotal),
  discountTotal: dec(discountTotal),
  buyerChargeTotal: dec(buyerChargeTotal),
  sellerCostTotal: dec(sellerCostTotal),
  passThroughTotal: dec(passThroughTotal),
  buyerTotal: dec(buyerTotal),
  netRevenue: dec(netRevenue),
  cogs: dec(cogs),
  grossProfit: dec(grossProfit),
  netProfit: dec(netProfit),
  netMargin: dec(netMargin),
);

Transaction ledgerTransaction({
  String id = 'txn-1',
  String code = 'S-202608-0041',
  TransactionType type = TransactionType.sale,
  DateTime? occurredAt,
  TransactionMoney? money,
  List<TransactionLine>? lines,
  List<TransactionFee> fees = const [],
  String? counterparty,
  PaymentMethod? paymentMethod = PaymentMethod.card,
  WriteOffReason? reason,
  String? reasonNote,
  String? note,
  DateTime? amendedAt,
  DateTime? updatedTime,
}) => Transaction(
  id: id,
  storeId: 'store-1',
  type: type,
  code: code,
  occurredAt: occurredAt ?? DateTime(2026, 8, 26, 9, 12),
  money: money ?? ledgerMoney(),
  lines: lines ?? [ledgerLine()],
  fees: fees,
  counterparty: counterparty,
  paymentMethod: paymentMethod,
  reason: reason,
  reasonNote: reasonNote,
  note: note,
  amendedAt: amendedAt,
  createdTime: DateTime(2026, 8, 26, 9, 12),
  updatedTime: updatedTime ?? DateTime(2026, 8, 26, 9, 12),
);
